### ISSUE TITLE
Pull Error Github Desktop

### ISSUE THREAD

**Issue by TimElbers** [Panchamy/TIL6010#6]
When trying to pull Github Desktop gives the following Error:

![image](https://user-images.githubusercontent.com/89917231/134325121-b427ddff-a3a6-4621-9599-f08b56e97086.png)

warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

error: The following untracked working tree files would be overwritten by merge:
	Assignments/.ipynb_checkpoints/Assignment 1 - Data Imports-checkpoint.ipynb
Please move or remove them before you merge.
Aborting
Updating 62fdcfc..f9f2288

Does anyone know how to fix this?

**Comment by Panchamy** [comment]
Hey, 

This usually happens when you make changes to your local folder but is not synced to the remote repository. Assuming this pull is for the TIL6010 repository and not your personal assignment repository, you can use the following solutions:
[command prompt solution](https://stackoverflow.com/questions/4157189/git-pull-while-ignoring-local-changes)
[GitHub desktop solution](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/stashing-changes)

If it is for your personal assignment repository, check out how to resolve merge conflict in GitHub - https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts
