### ISSUE TITLE
Trouble with question 3 of assignment 2 

### ISSUE THREAD

**Issue by anoukg4000** [Panchamy/TIL6010#7]
If I print the mean without the def function, it works and with it doesn't. I haven't been able to figure out what I'm doing wrong. Could you help m
![Code does not work](https://user-images.githubusercontent.com/89969095/134491937-37026a73-095b-41b2-ac84-07f1a9a59107.png)
![Code works](https://user-images.githubusercontent.com/89969095/134491948-d72cdec8-0578-46e4-9ddf-e329a3bd6ea5.png)

**Comment by nguyenthientin** [comment]
Hi Anouk,

I notice a few things:
- mean is a method of dataframe, so I believe you should call it like dataframe.mean()
- In cell [15], the statistic argument should be a string. That means when calling the function, you should provide 'mean' instead of mean (without the quotation marks). Without the quotation marks (like what you did), python with interpret mean as either a function or a variable.
- In cell [8], inside the function, statistic is seen as a variable. Its value is passed to the function when you make call. So, in line 14, when you call data[attributes].statistic, python will try to understand that statistic is a column name or a function.

Let me know if this clears your doubts.

**Comment by anoukg4000** [comment]
Then how am I supposed to use statistic in the code? I don't think I'm allowed to just write .mean in line 14 in cell [8]. Even if I try that, I am not getting the right answe
![fout 3](https://user-images.githubusercontent.com/89969095/134515602-d725d5e2-6d1e-4139-bf63-2533522da523.png)
r

**Comment by anoukg4000** [comment]
Okay, I had to get rid of the quotations around year. Still, am I allowed to put the .mean in line 17 as I did in my newest photo?

**Comment by nguyenthientin** [comment]
You can, but remember that mean is a function, so you need to write mean().
Also, to know if you need to call mean or min/max, etc, you can just check what value is in the variable `statistic`. A simple If..elif..else will do.

**Comment by anoukg4000** [comment]
Thank you for the help! I managed the question

**Comment by nguyenthientin** [comment]
Glad to hear that, Anouk!
